name: Code Formatter
on:
  pull_request:
    types:
      - labeled
jobs:
  autoformat:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'autoformat')
    steps:
      - name: Check we're not running on a fork. Autoformat cannot be used on forks.
        if: ${{ ! startsWith(github.event.pull_request.head.label, 'GoogleCloudPlatform') }}
        run: exit 1
      - name: Remove autoformat label
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'autoformat'
            })
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14'
      - name: Install goimports
        run: go get golang.org/x/tools/cmd/goimports
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Specify ref to get a working git environment.
          ref: ${{ github.event.pull_request.head.ref }}
      - run: goimports -w .
      - name: Run go mod tidy on all modules
        run: find . -name go.mod -execdir go mod tidy \;
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name yoshi-automation
          git config user.email yoshi-automation@google.com
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit --author "yoshi-automation <yoshi-automation@google.com>" --message "Run goimports and go mod tidy"
            git push
          fi
